- name: Directories are created
  file:
    path: "{{ item }}"
    state: directory
  with_items: directories
  tags: [consul]

- name: Files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: files
  tags: [consul]

- name: Is running
  shell: "nohup consul agent {{ consul_extra }} \
    -data-dir /data/consul/data \
    -config-dir /data/consul/config \
    -node={{ ansible_hostname }} \
    -bind={{ ip }} \
    -client=0.0.0.0 \
    >{{ logs_dir }}/consul.log 2>&1 &"
  tags: [consul]

- name: Has joined
  shell: consul join {{ consul_server_ip }}
  when: consul_server_ip is defined
  tags: [consul]
