home: /data/jenkins
main_job_src: service-workflow-config.xml

configs: [
  { src: "cd-config.xml", dir: "/data/jenkins/nodes/cd", file: "config.xml", mode: "0777" },
  { src: "credentials.xml", dir: "/data/jenkins", file: "credentials.xml", mode: "0777" },
  { src: "scriptApproval.xml", dir: "/data/jenkins", file: "scriptApproval.xml", mode: "0644" }
]

jobs: [
  {
     name: "simple-pipeline",
     service_name: "books-ms",
     src: "simple-pipeline-config.xml"
   }
]

plugins:
  - git
  - copyartifact
  - workflow-aggregator
  - workflow-multibranch
  - docker-workflow
